const fs = require('fs');

const path = 'c:/Users/rishi/Projects/Demo/web/components/LanguageContext.tsx';

let content = fs.readFileSync(path, 'utf8');

// We will inject keys via string replacement.
const newKeys = {
    English: `
        total: "total",
        your_analysis: "Your Analysis",
        primary_focus: "Primary Financial Focus",
        objective_summary: "Objective Contextual Summary",
        financial_suggestions: "Financial Suggestions",
        financial_disclaimer: "The Financial Suggestions contain information for suggestive purposes only, and should not be taken as professional or legal advice and we assume no liability for any errors, omissions, or financial decisions made based on its suggestions",
        topic_spread: "Aggregated Topic Spread (%)",
        ambient_subtext: "Globally enable or disable auto-recording listener",
        disable_suggestions: "Disable Financial Suggestions",
        disable_suggestions_sub: "Hide the AI actionable suggestions tracker from your Transcripts & Global dashboards",
        security_settings: "Security Settings",
        forgot_pin: "Forgot or Reset PIN?",
        pin_status: "PIN Status",
        pin_status_sub: "Active and safeguarding your preferences.",
        req_transcripts: "Require PIN for Transcripts",
        req_transcripts_sub: "Demand PIN entry when viewing History",
        req_analytics: "Require PIN for Global Analytics",
        req_analytics_sub: "Block access to the Fractional CFO dashboard",
        req_lock: "Require PIN for Lock/Unlock Feature",
        req_lock_sub: "Validates authentication when toggling edit blocks",
        sign_out_acc: "Sign Out of Account"
    `,
    Hindi: `
        total: "कुल",
        your_analysis: "आपका विश्लेषण",
        primary_focus: "प्राथमिक फोकस",
        objective_summary: "उद्देश्य सारांश",
        financial_suggestions: "वित्तीय सुझाव",
        financial_disclaimer: "वित्तीय सुझावों में केवल सुझावात्मक उद्देश्यों के लिए जानकारी होती है, इसे पेशेवर सलाह के रूप में नहीं लिया जाना चाहिए।",
        topic_spread: "एकत्रित विषय वितरण (%)",
        ambient_subtext: "ऑटो-रिकॉर्डिंग श्रोता को सक्षम या अक्षम करें",
        disable_suggestions: "वित्तीय सुझाव अक्षम करें",
        disable_suggestions_sub: "अपने डैशबोर्ड से AI सुझाव ट्रैकर को छुपाएं",
        security_settings: "सुरक्षा सेटिंग्स",
        forgot_pin: "पिन भूल गए या रीसेट करें?",
        pin_status: "पिन स्थिति",
        pin_status_sub: "सक्रिय और आपकी प्राथमिकताओं की सुरक्षा कर रहा है।",
        req_transcripts: "रिकॉर्डिंग के लिए पिन आवश्यक है",
        req_transcripts_sub: "इतिहास देखते समय पिन दर्ज करने की मांग करें",
        req_analytics: "ग्लोबल एनालिटिक्स के लिए पिन आवश्यक है",
        req_analytics_sub: "भिन्नात्मक सीएफओ डैशबोर्ड तक पहुंच को ब्लॉक करें",
        req_lock: "लॉक फीचर के लिए पिन आवश्यक है",
        req_lock_sub: "लॉकिंग करते समय प्रमाणीकरण को मान्य करता है",
        sign_out_acc: "खाते से साइन आउट करें"
    `,
    Bengali: `
        total: "মোট",
        your_analysis: "আপনার বিশ্লেষণ",
        primary_focus: "প্রাথমিক ফোকাস",
        objective_summary: "উদ্দেশ্যমূলক সারাংশ",
        financial_suggestions: "আর্থিক পরামর্শ",
        financial_disclaimer: "আর্থিক পরামর্শ শুধুমাত্র প্রস্তাবমূলক, পেশাদার পরামর্শ হিসাবে গ্রহণ করা উচিত নয়।",
        topic_spread: "একত্রিত বিষয় বিস্তার (%)",
        ambient_subtext: "অটো-রেকর্ডিং বিশ্বস্তরূপে সক্ষম বা নিষ্ক্রিয় করুন",
        disable_suggestions: "আর্থিক পরামর্শ নিষ্ক্রিয় করুন",
        disable_suggestions_sub: "আপনার ড্যাশবোর্ড থেকে এআই পরামর্শ ট্র্যাকার লুকান",
        security_settings: "নিরাপত্তা সেটিংস",
        forgot_pin: "পিন ভুলে গেছেন বা রিসেট করবেন?",
        pin_status: "পিনের অবস্থা",
        pin_status_sub: "সক্রিয় এবং আপনার পছন্দগুলি নিরাপদ করছে।",
        req_transcripts: "রেকর্ডিংয়ের জন্য পিন প্রয়োজন",
        req_transcripts_sub: "ইতিহাস দেখার সময় পিন এন্ট্রির দাবি করুন",
        req_analytics: "বিশ্লেষণের জন্য পিন প্রয়োজন",
        req_analytics_sub: "সিএফও ড্যাশবোর্ডে প্রবেশ বন্ধ করুন",
        req_lock: "লক বৈশিষ্ট্যের জন্য পিন প্রয়োজন",
        req_lock_sub: "লক করার সময় প্রমাণীকরণ বৈধ করে",
        sign_out_acc: "অ্যাকাউন্ট থেকে সাইন আউট করুন"
    `,
    Tamil: `
        total: "மொத்தம்",
        your_analysis: "உங்கள் பகுப்பாய்வு",
        primary_focus: "முதன்மை கவனம்",
        objective_summary: "குறிக்கோள் சுருக்கம்",
        financial_suggestions: "நிதி ஆலோசனைகள்",
        financial_disclaimer: "பரிந்துரைகளுக்கு மட்டுமே, தொழில்முறை ஆலோசனையாக எடுத்துக் கொள்ளக்கூடாது.",
        topic_spread: "பொருள் பரவல் (%)",
        ambient_subtext: "தானியங்கி பதிவு கேட்பானை இயக்கவும்",
        disable_suggestions: "நிதி ஆலோசனைகளை முடக்கு",
        disable_suggestions_sub: "உங்கள் டாஷ்போர்டில் இருந்து AI ஆலோசனைகளை மறைக்கவும்",
        security_settings: "பாதுகாப்பு அமைப்புகள்",
        forgot_pin: "பின் மறந்துவிட்டதா அல்லது மீட்டமைக்க வேண்டுமா?",
        pin_status: "பின் நிலை",
        pin_status_sub: "செயலில் உள்ளது, பாதுகாக்கிறது.",
        req_transcripts: "பதிவுகளுக்கு பின் தேவை",
        req_transcripts_sub: "வரலாற்றைப் பார்க்கும்போது பின்னை உள்ளிடுக",
        req_analytics: "பகுப்பாய்வுக்கு பின் தேவை",
        req_analytics_sub: "பகுப்பாய்வு அணுகலைத் தடு",
        req_lock: "பூட்டுக்கு பின் தேவை",
        req_lock_sub: "அங்கீகாரத்தை சரிபார்க்கிறது",
        sign_out_acc: "கணக்கிலிருந்து வெளியேறு"
    `,
    Telugu: `
        total: "మొత్తం",
        your_analysis: "మీ విశ్లేషణ",
        primary_focus: "ప్రాథమిక దృష్టి",
        objective_summary: "ఆబ్జెక్టివ్ సారాంశం",
        financial_suggestions: "ఆర్థిక సూచనలు",
        financial_disclaimer: "సూచన ప్రయోజనాల కోసం మాత్రమే, వృత్తిపరమైన సలహాగా తీసుకోకూడదు.",
        topic_spread: "కలిపిన విషయం వ్యాప్తి (%)",
        ambient_subtext: "ఆటో-రికార్డింగ్ వినడాన్ని ప్రారంభించండి లేదా నిలిపివేయండి",
        disable_suggestions: "ఆర్థిక సూచనలను నిలిపివేయండి",
        disable_suggestions_sub: "డాష్‌బోర్డ్ నుండి AI సూచనలను దాచండి",
        security_settings: "భద్రతా సెట్టింగులు",
        forgot_pin: "పిన్‌ను మర్చిపోయారా లేదా రీసెట్ చేయాలా?",
        pin_status: "పిన్ స్థితి",
        pin_status_sub: "క్రియాశీల మరియు భద్రత.",
        req_transcripts: "చరిత్రకు పిన్ అవసరం",
        req_transcripts_sub: "చరిత్రను చూసేటప్పుడు పిన్ అడగండి",
        req_analytics: "విశ్లేషణకు పిన్ అవసరం",
        req_analytics_sub: "డాష్‌బోర్డ్ ప్రాప్యతను నిరోధించండి",
        req_lock: "లాక్ కోసం పిన్ అవసరం",
        req_lock_sub: "పాస్‌వర్డ్‌ను ధృవీకరిస్తుంది",
        sign_out_acc: "ఖాతా నుండి సైన్ అవుట్ చేయండి"
    `,
    Gujarati: `
        total: "કુલ",
        your_analysis: "તમારું વિશ્લેષણ",
        primary_focus: "પ્રાથમિક ધ્યાન",
        objective_summary: "ઉદ્દેશ્ય સારાંશ",
        financial_suggestions: "નાણાકીય સૂચનો",
        financial_disclaimer: "માત્ર સૂચનાत्मक હેતુઓ માટે, વ્યાવસાયિક સલાહ તરીકે ન લેવું.",
        topic_spread: "એકત્રિત વિષય ફેલાવો (%)",
        ambient_subtext: "ઓટો-રેકોર્ડિંગ સાંભળનારને સક્ષમ અથવા અક્ષમ કરો",
        disable_suggestions: "નાણાકીય સૂચનો અક્ષમ કરો",
        disable_suggestions_sub: "ડેશબોર્ડમાંથી AI સૂચનો છુપાવો",
        security_settings: "સુરક્ષા સેટિંગ્સ",
        forgot_pin: "પિન ભૂલી ગયા છો કે રીસેટ કરવો છે?",
        pin_status: "પિન સ્થિતિ",
        pin_status_sub: "સક્રિય અને તમારી પસંદગીઓને સુરક્ષિત કરી રહ્યું છે.",
        req_transcripts: "ઇતિહાસ માટે પિન આવશ્યક છે",
        req_transcripts_sub: "ઇતિહાસ જોતી વખતે પિન દાખલ કરો",
        req_analytics: "વિશ્લેષણ માટે પિન આવશ્યક છે",
        req_analytics_sub: "ઍક્સેસને અવરોધિત કરો",
        req_lock: "લૉક માટે પિન આવશ્યક છે",
        req_lock_sub: "લૉક કરતી વખતે સુરક્ષા તપાસો",
        sign_out_acc: "એકાઉન્ટમાંથી સાઇન આઉટ કરો"
    `,
    Kannada: `
        total: "ಒಟ್ಟು",
        your_analysis: "ನಿಮ್ಮ ವಿಶ್ಲೇಷಣೆ",
        primary_focus: "ಪ್ರಾಥಮಿಕ ಗಮನ",
        objective_summary: "ಉದ್ದೇಶಿತ ಸಾರಾಂಶ",
        financial_suggestions: "ಆರ್ಥಿಕ ಸಲಹೆಗಳು",
        financial_disclaimer: "ಸೂಚನಾತ್ಮಕ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ, ವೃತ್ತಿಪರ ಸಲಹೆಯಾಗಿ ತೆಗೆದುಕೊಳ್ಳಬಾರದು.",
        topic_spread: "ಒಗ್ಗೂಡಿಸಿದ ವಿಷಯ ಹರಡುವಿಕೆ (%)",
        ambient_subtext: "ಆಟೋ-ರೆಕಾರ್ಡಿಂಗ್ ಆಲಿಸುವಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
        disable_suggestions: "ಆರ್ಥಿಕ ಸಲಹೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
        disable_suggestions_sub: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಿಂದ AI ಸಲಹೆಗಳನ್ನು ಮರೆಮಾಡಿ",
        security_settings: "ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        forgot_pin: "ಪಿನ್ ಮರೆತಿರುವಿರಾ ಅಥವಾ ಮರುಹೊಂದಿಸಬೇಕೆ?",
        pin_status: "ಪಿನ್ ಸ್ಥಿತಿ",
        pin_status_sub: "ಸಕ್ರಿಯವಾಗಿದೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ.",
        req_transcripts: "ಇತಿಹಾಸಕ್ಕಾಗಿ ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_transcripts_sub: "ಇತಿಹಾಸವನ್ನು ನೋಡುವಾಗ ಪಿನ್ ನಮೂದಿಸಿ",
        req_analytics: "ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_analytics_sub: "ಪ್ರವೇಶವನ್ನು ನಿರ್ಬಂಧಿಸಿ",
        req_lock: "ಲಾಕ್ ಮಾಡಲು ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_lock_sub: "ಭದ್ರತೆಯನ್ನು ಮೌಲ್ಯೀಕರಿಸುತ್ತದೆ",
        sign_out_acc: "ಖಾತೆಯಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಿ"
    `,
    Malayalam: `
        total: "ആകെ",
        your_analysis: "നിങ്ങളുടെ വിശകലനം",
        primary_focus: "പ്രധാന ശ്രദ്ധ",
        objective_summary: "ലക്ഷ്യ സംഗ്രഹം",
        financial_suggestions: "സാമ്പത്തിക നിർദ്ദേശങ്ങൾ",
        financial_disclaimer: "നിർദ്ദേശ ആവശ്യങ്ങൾക്ക് മാത്രമുള്ളതാണ്, പ്രൊഫഷണൽ ഉപദേശമായി കണക്കാക്കരുത്.",
        topic_spread: "വിഷയ വ്യാപ്തി (%)",
        ambient_subtext: "ഓട്ടോ-റെക്കോർഡിംഗ് ശ്രോതാവിനെ പ്രവർത്തനക്ഷമമാക്കുക",
        disable_suggestions: "നിർദ്ദേശങ്ങൾ പ്രവർത്തനരഹിതമാക്കുക",
        disable_suggestions_sub: "ഡാഷ്‌ബോർഡിൽ നിന്ന് AI നിർദ്ദേശങ്ങൾ മറയ്ക്കുക",
        security_settings: "സുരക്ഷാ ക്രമീകരണങ്ങൾ",
        forgot_pin: "പിൻ മറന്നോ അതോ റീസെറ്റ് ചെയ്യണോ?",
        pin_status: "പിൻ നില",
        pin_status_sub: "സജീവവും സുരക്ഷിതവുമാണ്.",
        req_transcripts: "ചരിത്രത്തിന് പിൻ ആവശ്യമാണ്",
        req_transcripts_sub: "ചരിത്രം കാണുമ്പോൾ പിൻ നൽകുക",
        req_analytics: "വിശകലനത്തിന് പിൻ ആവശ്യമാണ്",
        req_analytics_sub: "ആക്സസ് തടയുക",
        req_lock: "ലോക്ക് ചെയ്യാൻ പിൻ ആവശ്യമാണ്",
        req_lock_sub: "സുരക്ഷ പരിശോധിക്കുന്നു",
        sign_out_acc: "സൈൻ ഔട്ട് ചെയ്യുക"
    `,
    Marathi: `
        total: "एकूण",
        your_analysis: "तुमचे विश्लेषण",
        primary_focus: "प्राथमिक लक्ष",
        objective_summary: "उद्दिष्ट सारांश",
        financial_suggestions: "वित्तीय सूचना",
        financial_disclaimer: "केवळ सूचकांसाठी, व्यावसायिक सल्ला म्हणून घेऊ नये.",
        topic_spread: "एकत्रित विषय वितरण (%)",
        ambient_subtext: "ऑटो-रेकॉर्डिंग श्रोता सक्षम करा",
        disable_suggestions: "वित्तीय सूचना अक्षम करा",
        disable_suggestions_sub: "डॅशबोर्डवरून एआय सूचना लपवा",
        security_settings: "सुरक्षा सेटिंग्ज",
        forgot_pin: "पिन विसरलात किंवा रिसेट करायचा आहे?",
        pin_status: "पिन स्थिती",
        pin_status_sub: "सक्रिय आणि सुरक्षित करत आहे.",
        req_transcripts: "इतिहासासाठी पिन आवश्यक आहे",
        req_transcripts_sub: "इतिहास पाहताना पिन प्रविष्ट करा",
        req_analytics: "विश्लेषणासाठी पिन आवश्यक आहे",
        req_analytics_sub: "प्रवेश प्रतिबंधित करा",
        req_lock: "लॉकसाठी पिन आवश्यक आहे",
        req_lock_sub: "सुरक्षा प्रमाणित करते",
        sign_out_acc: "खात्यातून साइन आउट करा"
    `,
    Punjabi: `
        total: "ਕੁੱਲ",
        your_analysis: "ਤੁਹਾਡਾ ਵਿਸ਼ਲੇਸ਼ਣ",
        primary_focus: "ਪ੍ਰਾਇਮਰੀ ਫੋਕਸ",
        objective_summary: "ਉਦੇਸ਼ ਦਾ ਸਾਰੰਸ਼",
        financial_suggestions: "ਵਿੱਤੀ ਸੁਝਾਅ",
        financial_disclaimer: "ਕੇਵਲ ਸੁਝਾਅ ਲਈ, ਪੇਸ਼ੇਵਰ ਸਲਾਹ ਵਜੋਂ ਨਹੀਂ ਲਿਆ ਜਾਣਾ ਚਾਹੀਦਾ।",
        topic_spread: "ਵਿਸ਼ੇ ਦਾ ਫੈਲਾਅ (%)",
        ambient_subtext: "ਆਟੋ-ਰਿਕਾਰਡਿੰਗ ਸੁਣਨ ਵਾਲੇ ਨੂੰ ਸਮਰੱਥ ਕਰੋ",
        disable_suggestions: "ਵਿੱਤੀ ਸੁਝਾਅ ਅਸਮਰੱਥ ਕਰੋ",
        disable_suggestions_sub: "ਡੈਸ਼ਬੋਰਡ ਤੋਂ AI ਸੁਝਾਅ ਲੁਕਾਓ",
        security_settings: "ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ",
        forgot_pin: "ਪਿੰਨ ਭੁੱਲ ਗਏ ਹੋ ਜਾਂ ਰੀਸੈਟ ਕਰਨਾ ਹੈ?",
        pin_status: "ਪਿੰਨ ਸਥਿਤੀ",
        pin_status_sub: "ਸਰਗਰਮ ਹੈ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰ ਰਿਹਾ ਹੈ।",
        req_transcripts: "ਇਤਿਹਾਸ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_transcripts_sub: "ਇਤਿਹਾਸ ਦੇਖਣ ਵੇਲੇ ਪਿੰਨ ਦਾਖਲ ਕਰੋ",
        req_analytics: "ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_analytics_sub: "ਪਹੁੰਚ ਨੂੰ ਰੋਕੋ",
        req_lock: "ਲਾਕ ਕਰਨ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_lock_sub: "ਪ੍ਰਮਾਣਿਕਤਾ ਦੀ ਜਾਂਚ ਕਰਦਾ ਹੈ",
        sign_out_acc: "ਖਾਤੇ ਤੋਂ ਸਾਈਨ ਆਊਟ ਕਰੋ"
    `,
    Odia: `
        total: "ମୋଟ",
        your_analysis: "ଆପଣଙ୍କର ବିଶ୍ଳେଷଣ",
        primary_focus: "ପ୍ରାଥମିକ ଧ୍ୟାନ",
        objective_summary: "ଉଦ୍ଦେଶ୍ୟ ସାରାଂଶ",
        financial_suggestions: "ଆର୍ଥିକ ପରାମର୍ଶ",
        financial_disclaimer: "କେବଳ ପରାମର୍ଶ ପାଇଁ, ପେସାଦାର ପରାମର୍ଶ ନୁହେଁ |",
        topic_spread: "ବିଷୟ ବିସ୍ତାର (%)",
        ambient_subtext: "ଅଟୋ-ରେକର୍ଡିଂ ଶ୍ରୋତାକୁ ସକ୍ଷମ କରନ୍ତୁ",
        disable_suggestions: "ଆର୍ଥିକ ପରାମର୍ଶ ଅକ୍ଷମ କରନ୍ତୁ",
        disable_suggestions_sub: "ଡ୍ୟାସବୋର୍ଡରୁ AI ପରାମର୍ଶ ଲୁଚାନ୍ତୁ",
        security_settings: "ସୁରକ୍ଷା ସେଟିଂସମୂହ",
        forgot_pin: "ପିନ୍ ଭୁଲିଗଲେ କିମ୍ବା ରିସେଟ୍ କରିବେ?",
        pin_status: "ପିନ୍ ସ୍ଥିତି",
        pin_status_sub: "ସକ୍ରିୟ ଏବଂ ସୁରକ୍ଷିତ କରୁଛି |",
        req_transcripts: "ଇତିହାସ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_transcripts_sub: "ଇତିହାସ ଦେଖିବା ବେଳେ ପିନ୍ ଦିଅନ୍ତୁ",
        req_analytics: "ଆନାଲିଟିକ୍ସ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_analytics_sub: "ପ୍ରବେଶକୁ ଅବରୋଧ କରନ୍ତୁ",
        req_lock: "ଲକ୍ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_lock_sub: "ପ୍ରମାଣୀକରଣ ଯାଞ୍ଚ କରେ",
        sign_out_acc: "ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ"
    `
};

for (const lang of Object.keys(newKeys)) {
    const endBraceRegex = new RegExp('(' + lang + ':\\s*{[\\s\\S]*?view_analytics:\\s*"[^"]*")(\\s*})');
    content = content.replace(endBraceRegex, `$1,\n${newKeys[lang]}\n$2`);
}

fs.writeFileSync(path, content, 'utf8');
