"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "English" | "Hindi" | "Bengali" | "Tamil" | "Telugu" | "Gujarati" | "Kannada" | "Malayalam" | "Marathi" | "Punjabi" | "Odia";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    English: {
        transcripts: "Transcripts",
        transcripts_empty: "Your transcripts will appear here.",
        analytics: "Analytics",
        analytics_desc: "Analytics on entity extraction, frequency, and transcript processing will be displayed here.",
        profile: "Profile & Settings",
        account_details: "Account Details",
        settings: "Settings",
        preferences_desc: "More preferences will appear here as the app grows.",
        record_audio: "Record Audio",
        capture_voice: "Capture your voice and watch it turn into text instantly.",
        recording: "Recording... Click to stop",
        click_to_start: "Click to start recording",
        processing: "Processing Audio...",
        transcript_label: "Transcript",
        no_transcript: "No transcript yet. Record something to see the magic!",
        sign_out: "Sign Out",
        ambient_title: "Enable Ambient Audio Recording?",
        ambient_desc_1: "Ambient Recording continuously listens to your audio and transcripts them.",
        ambient_desc_2: "Worried about security? Don't worry, we only listen for finance specific words.",
        ambient_desc_3: "You can always disable this option in settings.",
        enable: "Enable",
        skip: "Skip",
        ambient_live: "Ambient Recording is Live",
        ambient_off: "Ambient Recording is Off",
        allow_ambient_recording: "Allow Ambient Recording",
        search_transcripts: "Search transcripts...",
        most_recent: "Most Recent",
        oldest_first: "Oldest First",
        ambient: "Ambient",
        manual: "Manual",
        edit: "Edit",
        lock: "Lock",
        unlock: "Unlock",
        delete: "Delete",
        view_analytics: "View Analytics",
application_preferences: "Application Preferences",

        total: "total",
        your_analysis: "Your Analysis",
        primary_focus: "Primary Financial Focus",
        objective_summary: "Objective Contextual Summary",
        financial_suggestions: "Financial Suggestions",
        financial_disclaimer: "The Financial Suggestions contain information for suggestive purposes only, and should not be taken as professional or legal advice and we assume no liability for any errors, omissions, or financial decisions made based on its suggestions",
        topic_spread: "Aggregated Topic Spread (%)",
        ambient_subtext: "Globally enable or disable auto-recording listener",
        disable_suggestions: "Disable Financial Suggestions",
        disable_suggestions_sub: "Hide the AI actionable suggestions tracker from your Transcripts & Global dashboards",
        security_settings: "Security Settings",
        forgot_pin: "Forgot or Reset PIN?",
        pin_status: "PIN Status",
        pin_status_sub: "Active and safeguarding your preferences.",
        req_transcripts: "Require PIN for Transcripts",
        req_transcripts_sub: "Demand PIN entry when viewing History",
        req_analytics: "Require PIN for Global Analytics",
        req_analytics_sub: "Block access to the Fractional CFO dashboard",
        req_lock: "Require PIN for Lock/Unlock Feature",
        req_lock_sub: "Validates authentication when toggling edit blocks",
        sign_out_acc: "Sign Out of Account"
    

    },
    Hindi: {
        transcripts: "रिकॉर्डिंग",
        transcripts_empty: "आपकी रिकॉर्डिंग यहां दिखाई देंगी।",
        analytics: "एनालिटिक्स",
        analytics_desc: "आपकी एनालिटिक्स यहां दिखाई देंगी।",
        profile: "प्रोफ़ाइल और सेटिंग्स",
        account_details: "खाता विवरण",
        settings: "सेटिंग्स",
        preferences_desc: "ऐप के बढ़ने पर और प्राथमिकताएं यहां दिखाई देंगी।",
        record_audio: "ऑडियो रिकॉर्ड करें",
        capture_voice: "अपनी आवाज़ कैप्चर करें और इसे तुरंत टेक्स्ट में बदलते देखें।",
        recording: "रिकॉर्डिंग हो रही है... रोकने के लिए क्लिक करें",
        click_to_start: "रिकॉर्डिंग शुरू करने के लिए क्लिक करें",
        processing: "ऑडियो प्रोसेस हो रहा है...",
        transcript_label: "ट्रांसक्रिप्ट",
        no_transcript: "अभी तक कोई ट्रांसक्रिप्ट नहीं। जादू देखने के लिए कुछ रिकॉर्ड करें!",
        sign_out: "साइन आउट करें",
        ambient_title: "क्या एम्बिएंट ऑडियो रिकॉर्डिंग सक्षम करें?",
        ambient_desc_1: "एम्बिएंट रिकॉर्डिंग लगातार आपकी ऑडियो सुनती है और उन्हें ट्रांसक्रिप्ट करती है।",
        ambient_desc_2: "सुरक्षा को लेकर चिंतित हैं? चिंता न करें, हम केवल वित्त विशिष्ट शब्द सुनते हैं।",
        ambient_desc_3: "आप इस विकल्प को सेटिंग्स में कभी भी अक्षम कर सकते हैं।",
        enable: "सक्षम करें",
        skip: "छोड़ें",
        ambient_live: "एम्बिएंट रिकॉर्डिंग लाइव है",
        ambient_off: "एम्बिएंट रिकॉर्डिंग बंद है",
        allow_ambient_recording: "एम्बिएंट रिकॉर्डिंग की अनुमति दें",
        search_transcripts: "रिकॉर्डिंग खोजें...",
        most_recent: "नवीनतम",
        oldest_first: "सबसे पुराना",
        ambient: "एम्बिएंट",
        manual: "मैनुअल",
        edit: "संपादित करें",
        lock: "लॉक करें",
        unlock: "अनलॉक करें",
        delete: "हटाएं",
        view_analytics: "एनालिटिक्स देखें",
application_preferences: "एप्लिकेशन प्राथमिकताएं",

        total: "कुल",
        your_analysis: "आपका विश्लेषण",
        primary_focus: "प्राथमिक फोकस",
        objective_summary: "उद्देश्य सारांश",
        financial_suggestions: "वित्तीय सुझाव",
        financial_disclaimer: "वित्तीय सुझावों में केवल सुझावात्मक उद्देश्यों के लिए जानकारी होती है, इसे पेशेवर सलाह के रूप में नहीं लिया जाना चाहिए।",
        topic_spread: "एकत्रित विषय वितरण (%)",
        ambient_subtext: "ऑटो-रिकॉर्डिंग श्रोता को सक्षम या अक्षम करें",
        disable_suggestions: "वित्तीय सुझाव अक्षम करें",
        disable_suggestions_sub: "अपने डैशबोर्ड से AI सुझाव ट्रैकर को छुपाएं",
        security_settings: "सुरक्षा सेटिंग्स",
        forgot_pin: "पिन भूल गए या रीसेट करें?",
        pin_status: "पिन स्थिति",
        pin_status_sub: "सक्रिय और आपकी प्राथमिकताओं की सुरक्षा कर रहा है।",
        req_transcripts: "रिकॉर्डिंग के लिए पिन आवश्यक है",
        req_transcripts_sub: "इतिहास देखते समय पिन दर्ज करने की मांग करें",
        req_analytics: "ग्लोबल एनालिटिक्स के लिए पिन आवश्यक है",
        req_analytics_sub: "भिन्नात्मक सीएफओ डैशबोर्ड तक पहुंच को ब्लॉक करें",
        req_lock: "लॉक फीचर के लिए पिन आवश्यक है",
        req_lock_sub: "लॉकिंग करते समय प्रमाणीकरण को मान्य करता है",
        sign_out_acc: "खाते से साइन आउट करें"
    

    },
    Bengali: {
        transcripts: "রেকর্ডিং",
        transcripts_empty: "আপনার রেকর্ডিং এখানে প্রদর্শিত হবে।",
        analytics: "বিশ্লেষণ",
        analytics_desc: "আপনার বিশ্লেষণ এখানে প্রদর্শিত হবে।",
        profile: "প্রোফাইল এবং সেটিংস",
        account_details: "অ্যাকাউন্টের বিবরণ",
        settings: "সেটিংস",
        preferences_desc: "অ্যাপ বাড়ার সাথে সাথে আরও পছন্দ এখানে প্রদর্শিত হবে।",
        record_audio: "অডিও রেকর্ড করুন",
        capture_voice: "আপনার ভয়েস ক্যাপচার করুন এবং তাৎক্ষণিকভাবে এটি টেক্সটে রূপান্তরিত হতে দেখুন।",
        recording: "রেকর্ডিং হচ্ছে... থামাতে ক্লিক করুন",
        click_to_start: "রেকর্ডিং শুরু করতে ক্লিক করুন",
        processing: "অডিও প্রক্রিয়া করা হচ্ছে...",
        transcript_label: "ট্রান্সক্রিপ্ট",
        no_transcript: "এখনও কোনও ট্রান্সক্রিপ্ট নেই। জাদু দেখতে কিছু রেকর্ড করুন!",
        sign_out: "সাইন আউট করুন",
        ambient_title: "অ্যাম্বিয়েন্ট অডিও রেকর্ডিং সক্ষম করবেন?",
        ambient_desc_1: "অ্যাম্বিয়েন্ট রেকর্ডিং ক্রমাগত আপনার অডিও শুনে এবং সেগুলো ট্রান্সক্রিপ্ট করে।",
        ambient_desc_2: "নিরাপত্তা নিয়ে চিন্তিত? চিন্তা করবেন না, আমরা কেবল অর্থ সংক্রান্ত নির্দিষ্ট শব্দগুলি শুনি।",
        ambient_desc_3: "আপনি সর্বদা সেটিংসে এই বিকল্পটি নিষ্ক্রিয় করতে পারেন।",
        enable: "সক্ষম করুন",
        skip: "এড়িয়ে যান",
        ambient_live: "অ্যাম্বিয়েন্ট রেকর্ডিং লাইভ আছে",
        ambient_off: "অ্যাম্বিয়েন্ট রেকর্ডিং বন্ধ আছে",
        allow_ambient_recording: "অ্যাম্বিয়েন্ট রেকর্ডিংয়ের অনুমতি দিন",
        search_transcripts: "রেকর্ডিংগুলি অন্বেষণ করুন...",
        most_recent: "সবচেয়ে নতুন",
        oldest_first: "সবচেয়ে পুরনো",
        ambient: "অ্যাম্বিয়েন্ট",
        manual: "ম্যানুয়াল",
        edit: "সম্পাদনা করুন",
        lock: "লক করুন",
        unlock: "আনলক করুন",
        delete: "মুছে ফেলুন",
        view_analytics: "বিশ্লেষণ দেখুন",
application_preferences: "অ্যাপ্লিকেশন পছন্দসমূহ",

        total: "মোট",
        your_analysis: "আপনার বিশ্লেষণ",
        primary_focus: "প্রাথমিক ফোকাস",
        objective_summary: "উদ্দেশ্যমূলক সারাংশ",
        financial_suggestions: "আর্থিক পরামর্শ",
        financial_disclaimer: "আর্থিক পরামর্শ শুধুমাত্র প্রস্তাবমূলক, পেশাদার পরামর্শ হিসাবে গ্রহণ করা উচিত নয়।",
        topic_spread: "একত্রিত বিষয় বিস্তার (%)",
        ambient_subtext: "অটো-রেকর্ডিং বিশ্বস্তরূপে সক্ষম বা নিষ্ক্রিয় করুন",
        disable_suggestions: "আর্থিক পরামর্শ নিষ্ক্রিয় করুন",
        disable_suggestions_sub: "আপনার ড্যাশবোর্ড থেকে এআই পরামর্শ ট্র্যাকার লুকান",
        security_settings: "নিরাপত্তা সেটিংস",
        forgot_pin: "পিন ভুলে গেছেন বা রিসেট করবেন?",
        pin_status: "পিনের অবস্থা",
        pin_status_sub: "সক্রিয় এবং আপনার পছন্দগুলি নিরাপদ করছে।",
        req_transcripts: "রেকর্ডিংয়ের জন্য পিন প্রয়োজন",
        req_transcripts_sub: "ইতিহাস দেখার সময় পিন এন্ট্রির দাবি করুন",
        req_analytics: "বিশ্লেষণের জন্য পিন প্রয়োজন",
        req_analytics_sub: "সিএফও ড্যাশবোর্ডে প্রবেশ বন্ধ করুন",
        req_lock: "লক বৈশিষ্ট্যের জন্য পিন প্রয়োজন",
        req_lock_sub: "লক করার সময় প্রমাণীকরণ বৈধ করে",
        sign_out_acc: "অ্যাকাউন্ট থেকে সাইন আউট করুন"
    

    },
    Tamil: {
        transcripts: "பதிவுகள்",
        transcripts_empty: "உங்கள் பதிவுகள் இங்கே தோன்றும்.",
        analytics: "பகுப்பாய்வு",
        analytics_desc: "உங்கள் பகுப்பாய்வு இங்கே காண்பிக்கப்படும்.",
        profile: "சுயவிவரம் & அமைப்புகள்",
        account_details: "கணக்கு விவரங்கள்",
        settings: "அமைப்புகள்",
        preferences_desc: "பயன்பாடு வளரும்போது மேலும் விருப்பத்தேர்வுகள் இங்கே தோன்றும்.",
        record_audio: "ஆடியோவைப் பதிவுசெய்",
        capture_voice: "உங்கள் குரலைப் பிடித்து உடனடியாக அது உரையாக மாறுவதைப் பாருங்கள்.",
        recording: "பதிவு செய்யப்படுகிறது... நிறுத்த கிளிக் செய்யவும்",
        click_to_start: "பதிவு செய்ய தொடங்க கிளிக் செய்யவும்",
        processing: "ஆடியோ செயலாக்கப்படுகிறது...",
        transcript_label: "படியெடுத்தல்",
        no_transcript: "இன்னும் படியெடுத்தல் இல்லை. மாயத்தைக் காண எதையாவது பதிவு செய்யுங்கள்!",
        sign_out: "வெளியேறு",
        ambient_title: "சுற்றுப்புற ஆடியோ பதிவை இயக்கவா?",
        ambient_desc_1: "சுற்றுப்புற பதிவு தொடர்ந்து உங்கள் ஆடியோவைக் கேட்டு அவற்றை படியெடுக்கிறது.",
        ambient_desc_2: "பாதுகாப்பைப் பற்றி கவலைப்படுகிறீர்களா? கவலை வேண்டாம், நிதி தொடர்பான சொற்களை மட்டுமே கேட்கிறோம்.",
        ambient_desc_3: "அமைப்புகளில் இந்த விருப்பத்தை நீங்கள் எப்போதும் முடக்கலாம்.",
        enable: "இயக்கு",
        skip: "தவிர்",
        ambient_live: "சுற்றுப்புற பதிவு நேரலையில் உள்ளது",
        ambient_off: "சுற்றுப்புற பதிவு முடக்கப்பட்டுள்ளது",
        allow_ambient_recording: "சுற்றுப்புற பதிவை அனுமதி",
        search_transcripts: "பதிவுகளைத் தேடு...",
        most_recent: "மிக சமீபத்திய",
        oldest_first: "பழமையானது",
        ambient: "சுற்றுப்புற",
        manual: "கையேடு",
        edit: "திருத்து",
        lock: "பூட்டு",
        unlock: "திற",
        delete: "அழி",
        view_analytics: "பகுப்பாய்வுகளைக் காண்",
application_preferences: "பயன்பாட்டு விருப்பங்கள்",

        total: "மொத்தம்",
        your_analysis: "உங்கள் பகுப்பாய்வு",
        primary_focus: "முதன்மை கவனம்",
        objective_summary: "குறிக்கோள் சுருக்கம்",
        financial_suggestions: "நிதி ஆலோசனைகள்",
        financial_disclaimer: "பரிந்துரைகளுக்கு மட்டுமே, தொழில்முறை ஆலோசனையாக எடுத்துக் கொள்ளக்கூடாது.",
        topic_spread: "பொருள் பரவல் (%)",
        ambient_subtext: "தானியங்கி பதிவு கேட்பானை இயக்கவும்",
        disable_suggestions: "நிதி ஆலோசனைகளை முடக்கு",
        disable_suggestions_sub: "உங்கள் டாஷ்போர்டில் இருந்து AI ஆலோசனைகளை மறைக்கவும்",
        security_settings: "பாதுகாப்பு அமைப்புகள்",
        forgot_pin: "பின் மறந்துவிட்டதா அல்லது மீட்டமைக்க வேண்டுமா?",
        pin_status: "பின் நிலை",
        pin_status_sub: "செயலில் உள்ளது, பாதுகாக்கிறது.",
        req_transcripts: "பதிவுகளுக்கு பின் தேவை",
        req_transcripts_sub: "வரலாற்றைப் பார்க்கும்போது பின்னை உள்ளிடுக",
        req_analytics: "பகுப்பாய்வுக்கு பின் தேவை",
        req_analytics_sub: "பகுப்பாய்வு அணுகலைத் தடு",
        req_lock: "பூட்டுக்கு பின் தேவை",
        req_lock_sub: "அங்கீகாரத்தை சரிபார்க்கிறது",
        sign_out_acc: "கணக்கிலிருந்து வெளியேறு"
    

    },
    Telugu: {
        transcripts: "రికార్డింగ్‌లు",
        transcripts_empty: "మీ రికార్డింగ్‌లు ఇక్కడ కనిపిస్తాయి.",
        analytics: "విశ్లేషణలు",
        analytics_desc: "ఉనికి వెలికితీత, ఫ్రీక్వెన్సీ, ట్రాన్స్క్రిప్ట్ ప్రాసెసింగ్ యొక్క విశ్లేషణలు ఇక్కడ ప్రదర్శించబడతాయి.",
        profile: "ప్రొఫైల్ & సెట్టింగ్‌లు",
        account_details: "ఖాతా వివరాలు",
        settings: "సెట్టింగ్‌లు",
        preferences_desc: "యాప్ పెరిగేకొద్దీ మరిన్ని ప్రాధాన్యతలు ఇక్కడ కనిపిస్తాయి.",
        record_audio: "ఆడియో రికార్డ్ చేయండి",
        capture_voice: "మీ వాయిస్‌ని క్యాప్చర్ చేయండి మరియు తక్షణమే వచనంగా మారడాన్ని చూడండి.",
        recording: "రికార్డవుతోంది... ఆపడానికి క్లిక్ చేయండి",
        click_to_start: "రికార్డింగ్ ప్రారంభించడానికి క్లిక్ చేయండి",
        processing: "ఆడియో ప్రాసెస్ అవుతోంది...",
        transcript_label: "ట్రాన్స్‌క్రిప్ట్",
        no_transcript: "ఇంకా ట్రాన్స్‌క్రిప్ట్ లేదు. మ్యాజిక్ చూడటానికి ఏదైనా రికార్డ్ చేయండి!",
        sign_out: "సైన్ అవుట్ చేయండి",
        ambient_title: "పరిసర ఆడియో రికార్డింగ్‌ను ప్రారంభించాలా?",
        ambient_desc_1: "యాంబియంట్ రికార్డింగ్ నిరంతరం మీ ఆడియోను వింటుంది మరియు ట్రాన్సక్రిప్ట్ చేస్తుంది.",
        ambient_desc_2: "భద్రత గురించి ఆందోళన చెందుతున్నారా? చింతించకండి, మేము ఫైనాన్స్ నిర్దిష్ట పదాల కోసం మాత్రమే వింటాము.",
        ambient_desc_3: "మీరు సెట్టింగ్‌లలో ఈ ఎంపికను ఎల్లప్పుడూ నిలిపివేయవచ్చు.",
        enable: "ప్రారంభించు",
        skip: "వదిలేయు",
        ambient_live: "యాంబియంట్ రికార్డింగ్ ప్రత్యక్షంగా ఉంది",
        ambient_off: "యాంబియంట్ రికార్డింగ్ ఆఫ్‌లో ఉంది",
        allow_ambient_recording: "యాంబియంట్ రికార్డింగ్‌ని అనుమతించండి",
        search_transcripts: "ట్రాన్స్‌క్రిప్ట్‌లను శోధించండి...",
        most_recent: "ఇటీవలి",
        oldest_first: "పాతవి",
        ambient: "యాంబియంట్",
        manual: "మాన్యువల్",
        edit: "సవరించు",
        lock: "లాక్ చెయ్",
        unlock: "అన్‌లాక్",
        delete: "తొలగించు",
        view_analytics: "విశ్లేషణలను వీక్షించండి",
application_preferences: "అప్లికేషన్ ప్రాధాన్యతలు",

        total: "మొత్తం",
        your_analysis: "మీ విశ్లేషణ",
        primary_focus: "ప్రాథమిక దృష్టి",
        objective_summary: "ఆబ్జెక్టివ్ సారాంశం",
        financial_suggestions: "ఆర్థిక సూచనలు",
        financial_disclaimer: "సూచన ప్రయోజనాల కోసం మాత్రమే, వృత్తిపరమైన సలహాగా తీసుకోకూడదు.",
        topic_spread: "కలిపిన విషయం వ్యాప్తి (%)",
        ambient_subtext: "ఆటో-రికార్డింగ్ వినడాన్ని ప్రారంభించండి లేదా నిలిపివేయండి",
        disable_suggestions: "ఆర్థిక సూచనలను నిలిపివేయండి",
        disable_suggestions_sub: "డాష్‌బోర్డ్ నుండి AI సూచనలను దాచండి",
        security_settings: "భద్రతా సెట్టింగులు",
        forgot_pin: "పిన్‌ను మర్చిపోయారా లేదా రీసెట్ చేయాలా?",
        pin_status: "పిన్ స్థితి",
        pin_status_sub: "క్రియాశీల మరియు భద్రత.",
        req_transcripts: "చరిత్రకు పిన్ అవసరం",
        req_transcripts_sub: "చరిత్రను చూసేటప్పుడు పిన్ అడగండి",
        req_analytics: "విశ్లేషణకు పిన్ అవసరం",
        req_analytics_sub: "డాష్‌బోర్డ్ ప్రాప్యతను నిరోధించండి",
        req_lock: "లాక్ కోసం పిన్ అవసరం",
        req_lock_sub: "పాస్‌వర్డ్‌ను ధృవీకరిస్తుంది",
        sign_out_acc: "ఖాతా నుండి సైన్ అవుట్ చేయండి"
    

    },
    Gujarati: {
        transcripts: "રેકોર્ડિંગ્સ",
        transcripts_empty: "તમારા રેકોર્ડિંગ્સ અહીં દેખાશે.",
        analytics: "એનાલિટિક્સ",
        analytics_desc: "તમારા એનાલિટિક્સ અહીં દર્શાવવામાં આવશે.",
        profile: "પ્રોફાઇલ અને સેટિંગ્સ",
        account_details: "એકાઉન્ટ વિગતો",
        settings: "સેટિંગ્સ",
        preferences_desc: "એપ્લિકેશન વધે તેમ વધુ પસંદગીઓ અહીં દેખાશે.",
        record_audio: "ઓડિયો રેકોર્ડ કરો",
        capture_voice: "તમારો અવાજ કેપ્ચર કરો અને તેને તરત જ ટેક્સ્ટમાં ફેરવાતો જુઓ.",
        recording: "રેકોર્ડિંગ ચાલુ છે... રોકવા માટે ક્લિક કરો",
        click_to_start: "રેકોર્ડિંગ શરૂ કરવા માટે ક્લિક કરો",
        processing: "ઓડિયો પ્રક્રિયા થઈ રહી છે...",
        transcript_label: "ટ્રાન્સક્રિપ્ટ",
        no_transcript: "હજી કોઈ ટ્રાન્સક્રિપ્ટ નથી. જાદુ જોવા માટે કંઈક રેકોર્ડ કરો!",
        sign_out: "સાઇન આઉટ",
        ambient_title: "એમ્બિઅન્ટ ઓડિયો રેકોર્ડિંગ સક્ષમ કરો?",
        ambient_desc_1: "એમ્બિઅન્ટ રેકોર્ડિંગ સતત તમારો ઓડિયો સાંભળે છે અને તેને ટ્રાન્સક્રિપ્ટ કરે છે.",
        ambient_desc_2: "સુરક્ષા અંગે ચિંતિત છો? ચિંતા કરશો નહીં, અમે ફક્ત નાણાં સંબંધિત શબ્દો સાંભળીએ છીએ.",
        ambient_desc_3: "તમે હંમેશા સેટિંગ્સમાં આ વિકલ્પને અક્ષમ કરી શકો છો.",
        enable: "સક્ષમ કરો",
        skip: "છોડી દો",
        ambient_live: "એમ્બિઅન્ટ રેકોર્ડિંગ લાઇવ છે",
        ambient_off: "એમ્બિઅન્ટ રેકોર્ડિંગ બંધ છે",
        allow_ambient_recording: "એમ્બિઅન્ટ રેકોર્ડિંગની મંજૂરી આપો",
        search_transcripts: "ટ્રાન્સક્રિપ્ટ્સ શોધો...",
        most_recent: "સૌથી નવું",
        oldest_first: "સૌથી જૂનું",
        ambient: "એમ્બિઅન્ટ",
        manual: "મેન્યુઅલ",
        edit: "સંપાદિત કરો",
        lock: "લૉક",
        unlock: "અનલૉક",
        delete: "કાઢી નાખો",
        view_analytics: "એનાલિટિક્સ જુઓ",
application_preferences: "એપ્લિકેશન પસંદગીઓ",

        total: "કુલ",
        your_analysis: "તમારું વિશ્લેષણ",
        primary_focus: "પ્રાથમિક ધ્યાન",
        objective_summary: "ઉદ્દેશ્ય સારાંશ",
        financial_suggestions: "નાણાકીય સૂચનો",
        financial_disclaimer: "માત્ર સૂચનાत्मक હેતુઓ માટે, વ્યાવસાયિક સલાહ તરીકે ન લેવું.",
        topic_spread: "એકત્રિત વિષય ફેલાવો (%)",
        ambient_subtext: "ઓટો-રેકોર્ડિંગ સાંભળનારને સક્ષમ અથવા અક્ષમ કરો",
        disable_suggestions: "નાણાકીય સૂચનો અક્ષમ કરો",
        disable_suggestions_sub: "ડેશબોર્ડમાંથી AI સૂચનો છુપાવો",
        security_settings: "સુરક્ષા સેટિંગ્સ",
        forgot_pin: "પિન ભૂલી ગયા છો કે રીસેટ કરવો છે?",
        pin_status: "પિન સ્થિતિ",
        pin_status_sub: "સક્રિય અને તમારી પસંદગીઓને સુરક્ષિત કરી રહ્યું છે.",
        req_transcripts: "ઇતિહાસ માટે પિન આવશ્યક છે",
        req_transcripts_sub: "ઇતિહાસ જોતી વખતે પિન દાખલ કરો",
        req_analytics: "વિશ્લેષણ માટે પિન આવશ્યક છે",
        req_analytics_sub: "ઍક્સેસને અવરોધિત કરો",
        req_lock: "લૉક માટે પિન આવશ્યક છે",
        req_lock_sub: "લૉક કરતી વખતે સુરક્ષા તપાસો",
        sign_out_acc: "એકાઉન્ટમાંથી સાઇન આઉટ કરો"
    

    },
    Kannada: {
        transcripts: "ರೆಕಾರ್ಡಿಂಗ್ಸ್",
        transcripts_empty: "ನಿಮ್ಮ ರೆಕಾರ್ಡಿಂಗ್ಸ್ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.",
        analytics: "ಅನಾಲಿಟಿಕ್ಸ್",
        analytics_desc: "ನಿಮ್ಮ ಅನಾಲಿಟಿಕ್ಸ್ ಇಲ್ಲಿ ಪ್ರದರ್ಶಿಸಲಾಗುತ್ತದೆ.",
        profile: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್ಸ್",
        account_details: "ಖಾತೆ ವಿವರಗಳು",
        settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
        preferences_desc: "ಅಪ್ಲಿಕೇಶನ್ ಬೆಳೆದಂತೆ ಹೆಚ್ಚಿನ ಆದ್ಯತೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.",
        record_audio: "ಆಡಿಯೋ ರೆಕಾರ್ಡ್ ಮಾಡಿ",
        capture_voice: "ನಿಮ್ಮ ಧ್ವನಿಯನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಮತ್ತು ಅದು ತಕ್ಷಣ ಪಠ್ಯವಾಗಿ ಬದಲಾಗುವುದನ್ನು ನೋಡಿ.",
        recording: "ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
        click_to_start: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ",
        processing: "ಆಡಿಯೋ ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತಿದೆ...",
        transcript_label: "ಟ್ರಾನ್ಸ್ಕ್ರಿಪ್ಟ್",
        no_transcript: "ಇನ್ನೂ ಯಾವುದೇ ಟ್ರಾನ್ಸ್ಕ್ರಿಪ್ಟ್ ಇಲ್ಲ. ಮ್ಯಾಜಿಕ್ ನೋಡಲು ಏನಾದರೂ ರೆಕಾರ್ಡ್ ಮಾಡಿ!",
        sign_out: "ಸೈನ್ ಔಟ್ ಮಾಡಿ",
        ambient_title: "ಆಂಬಿಯೆಂಟ್ ಆಡಿಯೋ ರೆಕಾರ್ಡಿಂಗ್ ಸಕ್ರಿಯಗೊಳಿಸಬೇಕೆ?",
        ambient_desc_1: "ಆಂಬಿಯೆಂಟ್ ರೆಕಾರ್ಡಿಂಗ್ ನಿರಂತರವಾಗಿ ನಿಮ್ಮ ಆಡಿಯೊವನ್ನು ಕೇಳುತ್ತದೆ ಮತ್ತು ಪ್ರತಿಲೇಖನ ಮಾಡುತ್ತದೆ.",
        ambient_desc_2: "ಭದ್ರತೆಯ ಬಗ್ಗೆ ಚಿಂತೆ ಇದೆಯೇ? ಚಿಂತಿಸಬೇಡಿ, ನಾವು ಕೇವಲ ಹಣಕಾಸು ಪದಗಳನ್ನು ಮಾತ್ರ ಕೇಳುತ್ತೇವೆ.",
        ambient_desc_3: "ನೀವು ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ ಈ ಆಯ್ಕೆಯನ್ನು ಯಾವಾಗಲೂ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಬಹುದು.",
        enable: "ಸಕ್ರಿಯಗೊಳಿಸಿ",
        skip: "ಸ್ಕಿಪ್ ಮಾಡಿ",
        ambient_live: "ಆಂಬಿಯೆಂಟ್ ರೆಕಾರ್ಡಿಂಗ್ ಲೈವ್ ಆಗಿದೆ",
        ambient_off: "ಆಂಬಿಯೆಂಟ್ ರೆಕಾರ್ಡಿಂಗ್ ಆಫ್ ಆಗಿದೆ",
        allow_ambient_recording: "ಆಂಬಿಯೆಂಟ್ ರೆಕಾರ್ಡಿಂಗ್ ಅನುಮತಿಸಿ",
        search_transcripts: "ಪಠ್ಯಗಳನ್ನು ಹುಡುಕಿ...",
        most_recent: "ಇತ್ತೀಚಿನದು",
        oldest_first: "ಹಳೆಯದು",
        ambient: "ಆಂಬಿಯೆಂಟ್",
        manual: "ಮ್ಯಾನುಯಲ್",
        edit: "ಎಡಿಟ್",
        lock: "ಲಾಕ್",
        unlock: "ಅನ್ಲಾಕ್",
        delete: "ಅಳಿಸು",
        view_analytics: "ಅನಾಲಿಟಿಕ್ಸ್ ವೀಕ್ಷಿಸಿ",
application_preferences: "ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳು",

        total: "ಒಟ್ಟು",
        your_analysis: "ನಿಮ್ಮ ವಿಶ್ಲೇಷಣೆ",
        primary_focus: "ಪ್ರಾಥಮಿಕ ಗಮನ",
        objective_summary: "ಉದ್ದೇಶಿತ ಸಾರಾಂಶ",
        financial_suggestions: "ಆರ್ಥಿಕ ಸಲಹೆಗಳು",
        financial_disclaimer: "ಸೂಚನಾತ್ಮಕ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ, ವೃತ್ತಿಪರ ಸಲಹೆಯಾಗಿ ತೆಗೆದುಕೊಳ್ಳಬಾರದು.",
        topic_spread: "ಒಗ್ಗೂಡಿಸಿದ ವಿಷಯ ಹರಡುವಿಕೆ (%)",
        ambient_subtext: "ಆಟೋ-ರೆಕಾರ್ಡಿಂಗ್ ಆಲಿಸುವಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ",
        disable_suggestions: "ಆರ್ಥಿಕ ಸಲಹೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ",
        disable_suggestions_sub: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಿಂದ AI ಸಲಹೆಗಳನ್ನು ಮರೆಮಾಡಿ",
        security_settings: "ಭದ್ರತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        forgot_pin: "ಪಿನ್ ಮರೆತಿರುವಿರಾ ಅಥವಾ ಮರುಹೊಂದಿಸಬೇಕೆ?",
        pin_status: "ಪಿನ್ ಸ್ಥಿತಿ",
        pin_status_sub: "ಸಕ್ರಿಯವಾಗಿದೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ.",
        req_transcripts: "ಇತಿಹಾಸಕ್ಕಾಗಿ ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_transcripts_sub: "ಇತಿಹಾಸವನ್ನು ನೋಡುವಾಗ ಪಿನ್ ನಮೂದಿಸಿ",
        req_analytics: "ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_analytics_sub: "ಪ್ರವೇಶವನ್ನು ನಿರ್ಬಂಧಿಸಿ",
        req_lock: "ಲಾಕ್ ಮಾಡಲು ಪಿನ್ ಅಗತ್ಯವಿದೆ",
        req_lock_sub: "ಭದ್ರತೆಯನ್ನು ಮೌಲ್ಯೀಕರಿಸುತ್ತದೆ",
        sign_out_acc: "ಖಾತೆಯಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಿ"
    

    },
    Malayalam: {
        transcripts: "റെക്കോർഡിംഗുകൾ",
        transcripts_empty: "നിങ്ങളുടെ റെക്കോർഡിംഗുകൾ ഇവിടെ കാണിക്കും.",
        analytics: "അനലിറ്റിക്സ്",
        analytics_desc: "നിങ്ങളുടെ അനലിറ്റിക്സ് ഇവിടെ കാണിക്കുന്നതാണ്.",
        profile: "പ്രൊഫൈലും ക്രമീകരണങ്ങളും",
        account_details: "അക്കൗണ്ട് വിവരങ്ങൾ",
        settings: "ക്രമീകരണങ്ങൾ",
        preferences_desc: "ആപ്പ് വളരുന്നതനുസരിച്ച് കൂടുതൽ മുൻഗണനകൾ ഇവിടെ കാണിക്കും.",
        record_audio: "ഓഡിയോ റെക്കോർഡ് ചെയ്യുക",
        capture_voice: "നിങ്ങളുടെ ശബ്ദം പിടിച്ചെടുക്കുക, തൽക്ഷണം ടെക്സ്റ്റായി മാറുന്നത് കാണുക.",
        recording: "റെക്കോർഡ് ചെയ്യുന്നു... നിർത്താൻ ലോഗിൻ ചെയ്യുക",
        click_to_start: "റെക്കോർഡിംഗ് ആരംഭിക്കാൻ ലോഗിൻ ചെയ്യുക",
        processing: "ഓഡിയോ പ്രൊസസ്സ് ചെയ്യുന്നു...",
        transcript_label: "ട്രാൻസ്ക്രിപ്റ്റ്",
        no_transcript: "ഇതുവരെ ട്രാൻസ്ക്രിപ്റ്റ് ഒന്നുമില്ല. മാജിക് കാണാൻ എന്തെങ്കിലും റെക്കോർഡ് ചെയ്യുക!",
        sign_out: "സൈൻ ഔട്ട് ചെയ്യുക",
        ambient_title: "ആംബിയൻ്റ് ഓഡിയോ റെക്കോർഡിംഗ് പ്രവർത്തനക്ഷമമാക്കണോ?",
        ambient_desc_1: "ആംബിയൻ്റ് റെക്കോർഡിംഗ് നിരന്തരം നിങ്ങളുടെ ഓഡിയോ കേൾക്കുകയും പരിഭാഷപ്പെടുത്തുകയും ചെയ്യുന്നു.",
        ambient_desc_2: "സുരക്ഷയെക്കുറിച്ച് ആശങ്കയുണ്ടോ? പേടിക്കേണ്ട, സാമ്പത്തിക പദങ്ങൾ മാത്രമേ ഞങ്ങൾ ശ്രദ്ധിക്കാറുള്ളൂ.",
        ambient_desc_3: "ക്രമീകരണങ്ങളിൽ നിങ്ങൾക്ക് ഈ ഓപ്ഷൻ എപ്പോൾ വേണമെങ്കിലും പ്രവർത്തനരഹിതമാക്കാം.",
        enable: "പ്രവർത്തനക്ഷമമാക്കുക",
        skip: "ഒഴിവാക്കുക",
        ambient_live: "ആംബിയൻ്റ് റെക്കോർഡിംഗ് ലൈവ് ആണ്",
        ambient_off: "ആംബിയൻ്റ് റെക്കോർഡിംഗ് ഓഫാണ്",
        allow_ambient_recording: "ആംബിയൻ്റ് റെക്കോർഡിംഗ് അനുവദിക്കുക",
        search_transcripts: "രേഖകൾ തിരയുക...",
        most_recent: "ഏറ്റവും പുതിയവ",
        oldest_first: "പഴയവ",
        ambient: "ആംബിയൻ്റ്",
        manual: "മാനുവൽ",
        edit: "എഡിറ്റ്",
        lock: "ലോക്ക്",
        unlock: "അൺലോക്ക്",
        delete: "ഇല്ലാതാക്കുക",
        view_analytics: "അനലിറ്റിക്സ് കാണുക",
application_preferences: "ആപ്ലിക്കേഷൻ മുൻഗണനകൾ",

        total: "ആകെ",
        your_analysis: "നിങ്ങളുടെ വിശകലനം",
        primary_focus: "പ്രധാന ശ്രദ്ധ",
        objective_summary: "ലക്ഷ്യ സംഗ്രഹം",
        financial_suggestions: "സാമ്പത്തിക നിർദ്ദേശങ്ങൾ",
        financial_disclaimer: "നിർദ്ദേശ ആവശ്യങ്ങൾക്ക് മാത്രമുള്ളതാണ്, പ്രൊഫഷണൽ ഉപദേശമായി കണക്കാക്കരുത്.",
        topic_spread: "വിഷയ വ്യാപ്തി (%)",
        ambient_subtext: "ഓട്ടോ-റെക്കോർഡിംഗ് ശ്രോതാവിനെ പ്രവർത്തനക്ഷമമാക്കുക",
        disable_suggestions: "നിർദ്ദേശങ്ങൾ പ്രവർത്തനരഹിതമാക്കുക",
        disable_suggestions_sub: "ഡാഷ്‌ബോർഡിൽ നിന്ന് AI നിർദ്ദേശങ്ങൾ മറയ്ക്കുക",
        security_settings: "സുരക്ഷാ ക്രമീകരണങ്ങൾ",
        forgot_pin: "പിൻ മറന്നോ അതോ റീസെറ്റ് ചെയ്യണോ?",
        pin_status: "പിൻ നില",
        pin_status_sub: "സജീവവും സുരക്ഷിതവുമാണ്.",
        req_transcripts: "ചരിത്രത്തിന് പിൻ ആവശ്യമാണ്",
        req_transcripts_sub: "ചരിത്രം കാണുമ്പോൾ പിൻ നൽകുക",
        req_analytics: "വിശകലനത്തിന് പിൻ ആവശ്യമാണ്",
        req_analytics_sub: "ആക്സസ് തടയുക",
        req_lock: "ലോക്ക് ചെയ്യാൻ പിൻ ആവശ്യമാണ്",
        req_lock_sub: "സുരക്ഷ പരിശോധിക്കുന്നു",
        sign_out_acc: "സൈൻ ഔട്ട് ചെയ്യുക"
    

    },
    Marathi: {
        transcripts: "रेकॉर्डिंग्ज",
        transcripts_empty: "तुमचे रेकॉर्डिंग्ज येथे दिसतील.",
        analytics: "अॅनालिटिक्स",
        analytics_desc: "तुमचे अॅनालिटिक्स येथे प्रदर्शित केले जातील.",
        profile: "प्रोफाइल आणि सेटिंग्ज",
        account_details: "खात्याचे तपशील",
        settings: "सेटिंग्ज",
        preferences_desc: "अॅप जसजसे वाढेल तसतशी अधिक प्राधान्ये येथे दिसतील.",
        record_audio: "ऑडिओ रेकॉर्ड करा",
        capture_voice: "तुमचा आवाज कॅप्चर करा आणि तो त्वरित मजकुरात बदलताना पहा.",
        recording: "रेकॉर्डिंग सुरू आहे... थांबवण्यासाठी क्लिक करा",
        click_to_start: "रेकॉर्डिंग सुरू करण्यासाठी क्लिक करा",
        processing: "ऑडिओ प्रोसेस होत आहे...",
        transcript_label: "ट्रान्सक्रिप्ट",
        no_transcript: "अद्याप कोणतेही ट्रान्सक्रिप्ट नाही. जादू पाहण्यासाठी काहीतरी रेकॉर्ड करा!",
        sign_out: "साइन आउट करा",
        ambient_title: "अॅम्बियंट ऑडिओ रेकॉर्डिंग सक्षम करायचे काय?",
        ambient_desc_1: "अॅम्बियंट रेकॉर्डिंग सतत तुमचा ऑडिओ ऐकते आणि ट्रान्सक्रिप्ट करते.",
        ambient_desc_2: "सुरक्षेबद्दल चिंतित आहात? काळजी करू नका, आम्ही केवळ वित्त विशिष्ट शब्द ऐकतो.",
        ambient_desc_3: "तुम्ही सेटिंग्जमध्ये हा पर्याय कधीही अक्षम करू शकता.",
        enable: "सक्षम करा",
        skip: "वगळा",
        ambient_live: "अॅम्बियंट रेकॉर्डिंग लाइव्ह आहे",
        ambient_off: "अॅम्बियंट रेकॉर्डिंग बंद आहे",
        allow_ambient_recording: "अॅम्बियंट रेकॉर्डिंगला अनुमती द्या",
        search_transcripts: "रेकॉर्डिंग्ज शोधा...",
        most_recent: "नवीनतम",
        oldest_first: "सर्वात जुने",
        ambient: "अॅम्बियंट",
        manual: "मॅन्युअल",
        edit: "संपादित करा",
        lock: "लॉक करा",
        unlock: "अनलॉक करा",
        delete: "हटवा",
        view_analytics: "अॅनालिटिक्स पहा",
application_preferences: "अॅप प्राधान्ये",

        total: "एकूण",
        your_analysis: "तुमचे विश्लेषण",
        primary_focus: "प्राथमिक लक्ष",
        objective_summary: "उद्दिष्ट सारांश",
        financial_suggestions: "वित्तीय सूचना",
        financial_disclaimer: "केवळ सूचकांसाठी, व्यावसायिक सल्ला म्हणून घेऊ नये.",
        topic_spread: "एकत्रित विषय वितरण (%)",
        ambient_subtext: "ऑटो-रेकॉर्डिंग श्रोता सक्षम करा",
        disable_suggestions: "वित्तीय सूचना अक्षम करा",
        disable_suggestions_sub: "डॅशबोर्डवरून एआय सूचना लपवा",
        security_settings: "सुरक्षा सेटिंग्ज",
        forgot_pin: "पिन विसरलात किंवा रिसेट करायचा आहे?",
        pin_status: "पिन स्थिती",
        pin_status_sub: "सक्रिय आणि सुरक्षित करत आहे.",
        req_transcripts: "इतिहासासाठी पिन आवश्यक आहे",
        req_transcripts_sub: "इतिहास पाहताना पिन प्रविष्ट करा",
        req_analytics: "विश्लेषणासाठी पिन आवश्यक आहे",
        req_analytics_sub: "प्रवेश प्रतिबंधित करा",
        req_lock: "लॉकसाठी पिन आवश्यक आहे",
        req_lock_sub: "सुरक्षा प्रमाणित करते",
        sign_out_acc: "खात्यातून साइन आउट करा"
    

    },
    Punjabi: {
        transcripts: "ਰਿਕਾਰਡਿੰਗਾਂ",
        transcripts_empty: "ਤੁਹਾਡੀਆਂ ਰਿਕਾਰਡਿੰਗਾਂ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੀਆਂ।",
        analytics: "ਵਿਸ਼ਲੇਸ਼ਣ",
        analytics_desc: "ਤੁਹਾਡਾ ਵਿਸ਼ਲੇਸ਼ਣ ਇੱਥੇ ਪ੍ਰਦਰਸ਼ਿਤ ਕੀਤਾ ਜਾਵੇਗਾ।",
        profile: "ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸੈਟਿੰਗਾਂ",
        account_details: "ਖਾਤੇ ਦੇ ਵੇਰਵੇ",
        settings: "ਸੈਟਿੰਗਾਂ",
        preferences_desc: "ਐਪ ਦੇ ਵਧਣ ਨਾਲ ਹੋਰ ਤਰਜੀਹਾਂ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੀਆਂ।",
        record_audio: "ਆਡੀਓ ਰਿਕਾਰਡ ਕਰੋ",
        capture_voice: "ਆਪਣੀ ਆਵਾਜ਼ ਕੈਪਚਰ ਕਰੋ ਅਤੇ ਇਸਨੂੰ ਤੁਰੰਤ ਟੈਕਸਟ ਵਿੱਚ ਬਦਲਦਾ ਦੇਖੋ।",
        recording: "ਰਿਕਾਰਡਿੰਗ ਹੋ ਰਹੀ ਹੈ... ਰੋਕਣ ਲਈ ਕਲਿੱਕ ਕਰੋ",
        click_to_start: "ਰਿਕਾਰਡਿੰਗ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ",
        processing: "ਆਡੀਓ ਪ੍ਰੋਸੈਸ ਹੋ ਰਿਹਾ ਹੈ...",
        transcript_label: "ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ",
        no_transcript: "ਹਾਲੇ ਕੋਈ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਨਹੀਂ। ਜਾਦੂ ਦੇਖਣ ਲਈ ਕੁਝ ਰਿਕਾਰਡ ਕਰੋ!",
        sign_out: "ਸਾਈਨ ਆਊਟ",
        ambient_title: "ਕੀ ਐਂਬੀਅੰਟ ਆਡੀਓ ਰਿਕਾਰਡਿੰਗ ਯੋਗ ਕਰਨੀ ਹੈ?",
        ambient_desc_1: "ਐਂਬੀਅੰਟ ਰਿਕਾਰਡਿੰਗ ਲਗਾਤਾਰ ਤੁਹਾਡੀ ਆਡੀਓ ਸੁਣਦੀ ਹੈ ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਕਰਦੀ ਹੈ।",
        ambient_desc_2: "ਸੁਰੱਖਿਆ ਬਾਰੇ ਚਿੰਤਤ ਹੋ? ਚਿੰਤਾ ਨਾ ਕਰੋ, ਅਸੀਂ ਸਿਰਫ ਵਿੱਤ ਸੰਬੰਧੀ ਸ਼ਬਦਾਂ ਨੂੰ ਸੁਣਦੇ ਹਾਂ।",
        ambient_desc_3: "ਤੁਸੀਂ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਇਸ ਵਿਕਲਪ ਨੂੰ ਕਦੇ ਵੀ ਅਸਮਰੱਥ ਕਰ ਸਕਦੇ ਹੋ।",
        enable: "ਯੋਗ ਕਰੋ",
        skip: "ਛੱਡੋ",
        ambient_live: "ਐਂਬੀਅੰਟ ਰਿਕਾਰਡਿੰਗ ਲਾਈਵ ਹੈ",
        ambient_off: "ਐਂਬੀਅੰਟ ਰਿਕਾਰਡਿੰਗ ਬੰਦ ਹੈ",
        allow_ambient_recording: "ਐਂਬੀਅੰਟ ਰਿਕਾਰਡਿੰਗ ਦੀ ਆਗਿਆ ਦਿਓ",
        search_transcripts: "ਰਿਕਾਰਡਿੰਗਾਂ ਦੀ ਖੋਜ ਕਰੋ...",
        most_recent: "ਸਭ ਤੋਂ ਨਵਾਂ",
        oldest_first: "ਸਭ ਤੋਂ ਪੁਰਾਣਾ",
        ambient: "ਐਂਬੀਅੰਟ",
        manual: "ਮੈਨੂਅਲ",
        edit: "ਸੰਪਾਦਨ ਕਰੋ",
        lock: "ਲਾਕ",
        unlock: "ਅਨਲੌਕ",
        delete: "ਮਿਟਾਓ",
        view_analytics: "ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖੋ",
application_preferences: "ਐਪਲੀਕੇਸ਼ਨ ਤਰਜੀਹਾਂ",

        total: "ਕੁੱਲ",
        your_analysis: "ਤੁਹਾਡਾ ਵਿਸ਼ਲੇਸ਼ਣ",
        primary_focus: "ਪ੍ਰਾਇਮਰੀ ਫੋਕਸ",
        objective_summary: "ਉਦੇਸ਼ ਦਾ ਸਾਰੰਸ਼",
        financial_suggestions: "ਵਿੱਤੀ ਸੁਝਾਅ",
        financial_disclaimer: "ਕੇਵਲ ਸੁਝਾਅ ਲਈ, ਪੇਸ਼ੇਵਰ ਸਲਾਹ ਵਜੋਂ ਨਹੀਂ ਲਿਆ ਜਾਣਾ ਚਾਹੀਦਾ।",
        topic_spread: "ਵਿਸ਼ੇ ਦਾ ਫੈਲਾਅ (%)",
        ambient_subtext: "ਆਟੋ-ਰਿਕਾਰਡਿੰਗ ਸੁਣਨ ਵਾਲੇ ਨੂੰ ਸਮਰੱਥ ਕਰੋ",
        disable_suggestions: "ਵਿੱਤੀ ਸੁਝਾਅ ਅਸਮਰੱਥ ਕਰੋ",
        disable_suggestions_sub: "ਡੈਸ਼ਬੋਰਡ ਤੋਂ AI ਸੁਝਾਅ ਲੁਕਾਓ",
        security_settings: "ਸੁਰੱਖਿਆ ਸੈਟਿੰਗਾਂ",
        forgot_pin: "ਪਿੰਨ ਭੁੱਲ ਗਏ ਹੋ ਜਾਂ ਰੀਸੈਟ ਕਰਨਾ ਹੈ?",
        pin_status: "ਪਿੰਨ ਸਥਿਤੀ",
        pin_status_sub: "ਸਰਗਰਮ ਹੈ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰ ਰਿਹਾ ਹੈ।",
        req_transcripts: "ਇਤਿਹਾਸ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_transcripts_sub: "ਇਤਿਹਾਸ ਦੇਖਣ ਵੇਲੇ ਪਿੰਨ ਦਾਖਲ ਕਰੋ",
        req_analytics: "ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_analytics_sub: "ਪਹੁੰਚ ਨੂੰ ਰੋਕੋ",
        req_lock: "ਲਾਕ ਕਰਨ ਲਈ ਪਿੰਨ ਲੋੜੀਂਦਾ ਹੈ",
        req_lock_sub: "ਪ੍ਰਮਾਣਿਕਤਾ ਦੀ ਜਾਂਚ ਕਰਦਾ ਹੈ",
        sign_out_acc: "ਖਾਤੇ ਤੋਂ ਸਾਈਨ ਆਊਟ ਕਰੋ"
    

    },
    Odia: {
        transcripts: "ରେକର୍ଡିଂଗୁଡିକ",
        transcripts_empty: "ଆପଣଙ୍କର ରେକର୍ଡିଂ ଏଠାରେ ଦେଖାଯିବ |",
        analytics: "ଆନାଲିଟିକ୍ସ",
        analytics_desc: "ଆପଣଙ୍କର ଆନାଲିଟିକ୍ସ ଏଠାରେ ପ୍ରଦର୍ଶିତ ହେବ |",
        profile: "ପ୍ରୋଫାଇଲ୍ ଏବଂ ସେଟିଂସମୂହ",
        account_details: "ଆକାଉଣ୍ଟ୍ ବିବରଣୀ",
        settings: "ସେଟିଂସମୂହ",
        preferences_desc: "ଆପ୍ ବଢିବା ସହିତ ଅଧିକ ପସନ୍ଦ ଏଠାରେ ଦେଖାଯିବ |",
        record_audio: "ଅଡିଓ ରେକର୍ଡ କରନ୍ତୁ",
        capture_voice: "ଆପଣଙ୍କର ଭଏସ୍ କ୍ୟାପଚର୍ କରନ୍ତୁ ଏବଂ ଏହାକୁ ତୁରନ୍ତ ଟେକ୍ସଟରେ ପରିଣତ ହେବାର ଦେଖନ୍ତୁ |",
        recording: "ରେକର୍ଡିଂ ଚାଲିଛି... ବନ୍ଦ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ",
        click_to_start: "ରେକର୍ଡିଂ ସେଟ୍ ଅପ୍ କରିବାକୁ କ୍ଲିକ୍ କରନ୍ତୁ",
        processing: "ଆଡିଓ ସେଟ୍ ଅପ୍ ହେଉଛି...",
        transcript_label: "ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ",
        no_transcript: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ନାହିଁ। କିଛି ରେକର୍ଡ କରନ୍ତୁ!",
        sign_out: "ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ",
        ambient_title: "ଆମ୍ବିଏଣ୍ଟ୍ ଅଡିଓ ରେକର୍ଡିଂ ସକ୍ଷମ କରିବେ କି?",
        ambient_desc_1: "ଆମ୍ବିଏଣ୍ଟ୍ ରେକର୍ଡିଂ କ୍ରମାଗତ ଭାବରେ ଆପଣଙ୍କର ଅଡିଓ ଶୁଣେ ଏବଂ ତାହାକୁ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ କରେ |",
        ambient_desc_2: "ସୁରକ୍ଷା ବିଷୟରେ ଚିନ୍ତିତ କି? ଚିନ୍ତା କରନ୍ତୁ ନାହିଁ, ଆମେ କେବଳ ଅର୍ଥ ସମ୍ବନ୍ଧୀୟ ଶବ୍ଦଗୁଡ଼ିକୁ ଶୁଣୁ |",
        ambient_desc_3: "ଆପଣ ସବୁବେଳେ ସେଟିଂସମୂହରେ ଏହି ବିକଳ୍ପକୁ ଅକ୍ଷମ କରିପାରିବେ |",
        enable: "ସକ୍ଷମ କରନ୍ତୁ",
        skip: "ବାଦ୍ ଦିଅନ୍ତୁ",
        ambient_live: "ଆମ୍ବିଏଣ୍ଟ୍ ରେକର୍ଡିଂ ଲାଇଭ୍ ଅଛି",
        ambient_off: "ଆମ୍ବିଏଣ୍ଟ୍ ରେକର୍ଡିଂ ଅଫ୍ ଅଛି",
        allow_ambient_recording: "ଆମ୍ବିଏଣ୍ଟ୍ ରେକର୍ଡିଂ ପାଇଁ ଅନୁମତି ଦିଅନ୍ତୁ",
        search_transcripts: "ରେକର୍ଡିଂଗୁଡିକ ଖୋଜନ୍ତୁ...",
        most_recent: "ନବୀନତମ",
        oldest_first: "ସବୁଠାରୁ ପୁରୁଣା",
        ambient: "ଆମ୍ବିଏଣ୍ଟ୍",
        manual: "ମାନୁଆଲ୍",
        edit: "ଏଡିଟ୍ କରନ୍ତୁ",
        lock: "ଲକ୍ କରନ୍ତୁ",
        unlock: "ଅନଲକ୍ କରନ୍ତୁ",
        delete: "ଡିଲିଟ୍ କରନ୍ତୁ",
        view_analytics: "ଆନାଲିଟିକ୍ସ ଦେଖନ୍ତୁ",
application_preferences: "ଆପ୍ଲିକେସନ୍ ପସନ୍ଦଗୁଡିକ",

        total: "ମୋଟ",
        your_analysis: "ଆପଣଙ୍କର ବିଶ୍ଳେଷଣ",
        primary_focus: "ପ୍ରାଥମିକ ଧ୍ୟାନ",
        objective_summary: "ଉଦ୍ଦେଶ୍ୟ ସାରାଂଶ",
        financial_suggestions: "ଆର୍ଥିକ ପରାମର୍ଶ",
        financial_disclaimer: "କେବଳ ପରାମର୍ଶ ପାଇଁ, ପେସାଦାର ପରାମର୍ଶ ନୁହେଁ |",
        topic_spread: "ବିଷୟ ବିସ୍ତାର (%)",
        ambient_subtext: "ଅଟୋ-ରେକର୍ଡିଂ ଶ୍ରୋତାକୁ ସକ୍ଷମ କରନ୍ତୁ",
        disable_suggestions: "ଆର୍ଥିକ ପରାମର୍ଶ ଅକ୍ଷମ କରନ୍ତୁ",
        disable_suggestions_sub: "ଡ୍ୟାସବୋର୍ଡରୁ AI ପରାମର୍ଶ ଲୁଚାନ୍ତୁ",
        security_settings: "ସୁରକ୍ଷା ସେଟିଂସମୂହ",
        forgot_pin: "ପିନ୍ ଭୁଲିଗଲେ କିମ୍ବା ରିସେଟ୍ କରିବେ?",
        pin_status: "ପିନ୍ ସ୍ଥିତି",
        pin_status_sub: "ସକ୍ରିୟ ଏବଂ ସୁରକ୍ଷିତ କରୁଛି |",
        req_transcripts: "ଇତିହାସ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_transcripts_sub: "ଇତିହାସ ଦେଖିବା ବେଳେ ପିନ୍ ଦିଅନ୍ତୁ",
        req_analytics: "ଆନାଲିଟିକ୍ସ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_analytics_sub: "ପ୍ରବେଶକୁ ଅବରୋଧ କରନ୍ତୁ",
        req_lock: "ଲକ୍ ପାଇଁ ପିନ୍ ଆବଶ୍ୟକ",
        req_lock_sub: "ପ୍ରମାଣୀକରଣ ଯାଞ୍ଚ କରେ",
        sign_out_acc: "ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ"
    

    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>("English");

    useEffect(() => {
        const savedLang = localStorage.getItem("app_lang") as Language;
        if (savedLang && Object.keys(translations).includes(savedLang)) {
            setLanguage(savedLang);
        }
    }, []);

    const updateLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("app_lang", lang);
    };

    const t = (key: string) => {
        return translations[language][key as keyof typeof translations["English"]] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: updateLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
};
